images:
  repositoryDirname: docker.io/vr00mm
main:
  tag: "v2-latest"
  serviceType: ClusterIP
hats:
  tag: "v2-latest"
leftLeg:
  tag: "v2-latest"
leftArm:
  tag: "v2-latest"
rightLeg:
  tag: "v2-latest"
rightArm:
  tag: "v2-latest"

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
  - paths:
      path: "/"

service:
  port: 9000
