storage:
  type: sqlite3
  config:
    file: /var/dex/dex.db

service:
  ports:
    http:
      port: 5556
ingress:
  enabled: true
  className: nginx
  hosts:
  - paths:
      - path: "/"    
        pathType: "ImplementationSpecific"
