---
apiVersion: v1
kind: Namespace
metadata:
  name: podtato-kubectl
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-main
  labels:
    app: podtato-head
spec:
  selector:
    matchLabels:
      component: podtato-main
  template:
    metadata:
      labels:
        component: podtato-main
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ghcr.io/podtato-head/podtato-main:v1-latest-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        env:
        - name: PORT
          value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-main
  labels:
    app: podtato-head
spec:
  selector:
    component: podtato-main
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  type: LoadBalancer
  # change to NodePort if no LoadBalancer controller is available
  # type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-hats
  labels:
    app: podtato-head
spec:
  selector:
    matchLabels:
      component: podtato-hats
  template:
    metadata:
      labels:
        component: podtato-hats
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: docker.io/vr00mm/podtato-head-hats:v0.1.0
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args: ["sleep 15 && /podtatoserver"]
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
            - name: VERSION
              value: "v2"
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-hats
  labels:
    app: podtato-head
spec:
  selector:
    component: podtato-hats
  ports:
    - name: http
      port: 9001
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-left-leg
  labels:
    app: podtato-head
spec:
  selector:
    matchLabels:
      component: podtato-left-leg
  template:
    metadata:
      labels:
        component: podtato-left-leg
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image:  ghcr.io/podtato-head/podtato-left-leg:v1-latest-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-left-leg
  labels:
    app: podtato-head
spec:
  selector:
    component: podtato-left-leg
  ports:
    - name: http
      port: 9002
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-left-arm
  labels:
    app: podtato-head
spec:
  selector:
    matchLabels:
      component: podtato-left-arm
  template:
    metadata:
      labels:
        component: podtato-left-arm
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image:  ghcr.io/podtato-head/podtato-left-arm:v1-latest-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-left-arm
  labels:
    app: podtato-head
spec:
  selector:
    component: podtato-left-arm
  ports:
    - name: http
      port: 9003
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-right-leg
  labels:
    app: podtato-head
spec:
  selector:
    matchLabels:
      component: podtato-right-leg
  template:
    metadata:
      labels:
        component: podtato-right-leg
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image:  ghcr.io/podtato-head/podtato-right-leg:v1-latest-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-right-leg
  labels:
    app: podtato-head
spec:
  selector:
    component: podtato-right-leg
  ports:
    - name: http
      port: 9004
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podtato-right-arm
  labels:
    app: podtato-head
spec:
  selector:
    matchLabels:
      component: podtato-right-arm
  template:
    metadata:
      labels:
        component: podtato-right-arm
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image:  ghcr.io/podtato-head/podtato-right-arm:v1-latest-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
---
apiVersion: v1
kind: Service
metadata:
  name: podtato-right-arm
  labels:
    app: podtato-head
spec:
  selector:
    component: podtato-right-arm
  ports:
    - name: http
      port: 9005
      protocol: TCP
      targetPort: 9000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: podtato-head
spec:
  rules:
  - host: podtato-head.remi-ziolkowski.fr
    http:
      paths:
      - backend:
          service:
            name: podtato-head
            port:
              number: 9000
        path: /
        pathType: Prefix
