apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        ports:
          - containerPort: 8081
        env:
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "litmus-portal.fullname" . }}-admin-secret
                key: DB_USER
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "litmus-portal.fullname" . }}-admin-secret
                key: DB_PASSWORD
          - name: ME_CONFIG_MONGODB_SERVER
            value: {{ include "litmus-portal.fullname" . }}-mongo
