# .github/workflows/deploy.yml
name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  deploy-litmus:
    name: "Deploy Litmus Chaos Center Helm Chart"
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/docker-helm-client:v0.1.0
      env:
        KUBECONFIG: "/tmp/kubeconfig"
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Init Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          chmod 0600 /tmp/kubeconfig
      - name: Add Litmus Repository
        run: |
          helm repo add litmuschaos https://vr00mm.github.io
          helm repo update
      - name: Deploy Chart
        run: helm upgrade --install chaos-center litmuschaos/litmus --version "2.0.0" --namespace litmus --create-namespace -f ./values/litmus/common.yaml -f ./values/litmus/env-prod.yaml
      - name: Delete Kubeconfig
        run: rm /tmp/kubeconfig

  init-litmus:
    name: "Init Litmus Params Through API"
    needs: [deploy-litmus]
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/litmus-as-code:v0.1.0
      env:
        KUBECONFIG: "/tmp/kubeconfig"
        KUBE_CONTEXT: "minikube"
        LITMUS_URL: "http://127.0.0.1:9091"
        LITMUS_USERNAME : ${{ secrets.LITMUS_USERNAME }}
        LITMUS_PASSWORD : ${{ secrets.LITMUS_PASSWORD }}
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Init Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          chmod 0600 /tmp/kubeconfig
      - name: Configure Litmus
        run: "kubectl -n litmus port-forward svc/chaos-center-litmus-frontend-service 9091:9091 &"
      - run: "bash -x /entrypoint.sh ./values/litmus-as-code/configuration.json"
