# .github/workflows/deploy.yml
name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Deploy'
      uses: 'deliverybot/helm@v3'
      with:
        helm: 'helm3'
        release: 'litmus'
        namespace: 'chaos-center'
        chart: 'litmus'
        repository: 'https://litmuschaos.github.io/litmus-helm'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
