# .github/workflows/deploy.yml
name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  deploy-litmus:
    name: "Deploy Litmus Chaos Center Helm Chart"
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/docker-helm-client:v0.1.0
      env:
        KUBECONFIG: "${{ secrets.KUBECONFIG }}"
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Add Litmus Repository
        run: helm repo add litmuschaos https://litmuschaos.github.io/litmus-helm/
      - name: Update Repo
        run: helm repo update
      - name: Deploy Chart
        run: helm upgrade --install chaos-center litmuschaos/litmus --namespace litmus -f ./values/litmus/common.yaml -f ./values/litmus/env-prod.yaml
