# .github/workflows/deploy.yml
name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  deploy-oidc-provider:
    name: "Deploy OIDC Provider with yaml manifest"
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/docker-helm-client:v0.1.0
      env:
        KUBECONFIG: "/tmp/kubeconfig"
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Init Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          chmod 0600 /tmp/kubeconfig
      - name: Deploy Manifest
        run: |
          kubectl create namespace/oidc-provider || true
          kubectl -n 'oidc-provider' apply -f ./src/oidc-provider/manifest.yaml
      - name: Delete Kubeconfig
        run: rm /tmp/kubeconfig

  deploy-litmus:
    name: "Deploy Litmus Chaos Center Helm Chart"
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/docker-helm-client:v0.1.0
      env:
        KUBECONFIG: "/tmp/kubeconfig"
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Init Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          chmod 0600 /tmp/kubeconfig
      - name: Add Litmus Repository
        run: |
          helm repo add litmuschaos https://litmuschaos.github.io/litmus-helm/
          helm repo update
      - name: Deploy Chart
        run: helm upgrade --install chaos-center litmuschaos/litmus --namespace litmus --create-namespace -f ./values/litmus/common.yaml -f ./values/litmus/env-prod.yaml
      - name: Delete Kubeconfig
        run: rm /tmp/kubeconfig

  init-litmus:
    name: "Init Litmus Params Through API"
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/litmus-as-code:v0.1.0
      env:
        KUBECONFIG: "/tmp/kubeconfig"
        LITMUS_URL: ${{ secrets.LITMUS_URL }}
        LITMUS_USERNAME : ${{ secrets.LITMUS_USERNAME }}
        LITMUS_PASSWORD : ${{ secrets.LITMUS_PASSWORD }}
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Say Hello
        run: |
          echo "Hello"

  deploy-prometheus:
    name: "Deploy Monitoring stack"
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/docker-helm-client:v0.1.0
      env:
        KUBECONFIG: "/tmp/kubeconfig"
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Init Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          chmod 0600 /tmp/kubeconfig
      - name: Add prometheus-community Repository
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
      - name: Deploy Chart
        run: helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack
      - name: Delete Kubeconfig
        run: rm /tmp/kubeconfig
