# .github/workflows/deploy.yml
name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  init-litmus:
    name: "Init Litmus Params Through API"
    runs-on: "ubuntu-latest"
    container:
      image: vr00mm/litmus-as-code:v0.1.0
      env:
        KUBECONFIG: "/tmp/kubeconfig"
        LITMUS_URL: 127.0.0.1:8080
        LITMUS_USERNAME : ${{ secrets.LITMUS_USERNAME }}
        LITMUS_PASSWORD : ${{ secrets.LITMUS_PASSWORD }}
    steps:
      - name: Load Workspace
        uses: actions/checkout@v2
      - name: Init Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          chmod 0600 /tmp/kubeconfig
      - name: Configure Litmus
        run: "kubectl -n litmus port-forward svc/chaos-center-litmus-frontend-service 8080:9091 &"
      - run: "bash -x /entrypoint.sh"
